- name: Configure gateway
  hosts: gateway
  become: True
  tasks:
          - name: Set IP forwarding
            sysctl:
                     name="net.ipv4.ip_forward"
                     value="1"
                     state="present"
                     reload="yes"

          - name: Create interface
            net_interface:
                    name: eth1
                    state: up

          - name: Assign IP address to new interface
            net_l3_interface:
                    name: eth1
                    ipv4: 192.168.10.2/24


#          - name: Cheat creating interface
#            command: '{{ item }}'
#            with_items:
#                    - "ifconfig eth1 up"
#                    - "ifconfig eth1 192.168.10.1"

          - name: Configuring NAT functioning
            iptables:
                    table: nat
                    action: append
                    chain:  POSTROUTING
                    out_interface: eth0
                    jump: MASQUERADE


- name: Configure hostA
  hosts: hostA
  become: True
  tasks:
          - name: Cheat creating interface
            command: '{{ item }}'
            with_items:
                    - "ifconfig eth1 up"
                    - "ifconfig eth1 192.168.10.2"

          - name: Delete default static route
            net_static_route:
                    prefix: 0.0.0.0
                    mask: 0.0.0.0
                    gateway: 10.0.2.2
                    state: absent

          - name: Add default static route through gateway
            net_static_route:
                    prefix: 0.0.0.0
                    mask: 0.0.0.0
                    gateway: 192.168.10.1
                    state: present

