- name: Configure gateway
  hosts: gateway
  become: True
  tasks:
          - name: Set IP forwarding
            sysctl:
                     name="net.ipv4.ip_forward"
                     value="1"
                     state="present"
                     reload="yes"

          - name: Template eth1 file with private interface configuration
            template:
                    src: files/gw_eth1.cfg
                    dest: /etc/network/interfaces.d/eth1.cfg
            notify: ifup eth1

          - name: Configure NAT functioning
            iptables:
                    table: nat
                    action: append
                    chain:  POSTROUTING
                    out_interface: eth0
                    jump: MASQUERADE


  handlers:
          - name: ifup eth1
            command: "ifup eth1"
          
- name: Configure hostA
  hosts: hostA
  become: True
  tasks:
          - name: Add a line to interfaces file
            lineinfile:
                    path: /etc/network/interfaces
                    line: "{{ item }}"
            with_items:
                    - auto eth1
                    - iface eth1 inet static
          
          - name: Configure eth1 interface
            interfaces_file:
                    iface: eth1
                    option: "{{ item.option }}"
                    value: "{{ item.value }}"
            with_items:
                    - { option: 'address', value: '192.168.10.2' }
                    - { option: 'network', value: '192.168.10.0' }
                    - { option: 'netmask', value: '255.255.255.0' }
                    - { option: 'up', value: 'route del default dev eth0' }
                    - { option: 'up', value: 'route add default gw 192.168.10.1 dev eth1' }

            notify: ifup eth1

  handlers:
          - name: ifup eth1
            command: "ifup eth1"
    
